# Generated by Django 2.0.9 on 2024-09-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_date', models.CharField(max_length=100)),
                ('replay', models.CharField(max_length=100)),
                ('replay_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dealers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('DEALER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.dealers')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_rate', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=100)),
                ('material_image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.CharField(max_length=100)),
                ('DRIVER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.drivers')),
                ('ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
            ],
        ),
        migrations.CreateModel(
            name='order_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.CharField(max_length=100)),
                ('ammount', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('DEALER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.dealers')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=100)),
                ('DEALER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.dealers')),
                ('MATERIAL', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.material')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.users'),
        ),
        migrations.AddField(
            model_name='payment',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.users'),
        ),
        migrations.AddField(
            model_name='order_sub',
            name='STOCK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.stock'),
        ),
        migrations.AddField(
            model_name='order',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.users'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.users'),
        ),
        migrations.AddField(
            model_name='drivers',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.login'),
        ),
        migrations.AddField(
            model_name='dealers',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.login'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.users'),
        ),
    ]
